name: pytest-analog-release

on:
  release:
    types: [published]

  workflow_dispatch:

jobs:
  release-build:
    runs-on: self-hosted
    strategy:
      matrix:
        python-version: ["3.9"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Setup Python virtual environment
        run: python -m venv venv
      
      - name: Install dependencies
        run: |
          . venv\Scripts\activate
          python -m pip install --upgrade pip
          python -m pip install -i https://test.pypi.org/simple/ pysmu
          python -m pip install .
      
      - name: Run tests
        run: |
          . venv\Scripts\activate
          python -m pytest testing\test_pytest_analog_plugin.py

      - name: Build Wheel package
        run: |
          . venv\Scripts\activate
          python -m pip install --upgrade build
          python -m build -w

      - name: Upload Wheel Package
        uses: actions/upload-artifact@v4
        with:
          name: pytest-analog
          path: dist/

  test-pypi-publish:
    runs-on: ubuntu-latest

    needs:
      - release-build

    permissions:
      id-token: write

    # Dedicated environments with protections for publishing are strongly recommended.
    environment:
      name: testpypi
      url: https://test.pypi.org/p/pytest-analog

    steps:
      - name: Retrieve release distributions
        uses: actions/download-artifact@v4
        with:
          name: pytest-analog
          path: dist/

      - name: Publish release distributions to Test PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
